
def saveSignUpStudent (name,lastname,classroom,address,postcode,telephone,dishis,moadel,fathername,id):
    View.view_signup.SignUpStu()
    f = open("C:/Users/ASUS/Desktop/schooool/studentinfo.txt", "w")
    f.write("Name: " + name + "\n")
    f.write("Lastname: " + lastname + "\n")
    f.write("Classroom: " + classroom + "\n")
    f.write("Address: " + address + "\n")
    f.write("PostCode: " + postcode + "\n")
    f.write("Telephone: " + telephone + "\n")
    f.write("Diseases History: " + dishis + "\n")
    f.write("Moadel: " + moadel + "\n")
    f.write("Father's Name: " + fathername + "\n")
    f.write("ID: " + id + "\n")
    f.close()

def saveSignUpTeacher (name,last_name,lesson,telephone,qualification,age,teachExp, id):
    View.view_signup.SignUpStu()
    f = open("C:/Users/ASUS/Desktop/schooool/teacherinfo.txt", "w")
    f.write("Name: " + name + "\n")
    f.write("Lastname: " + last_name + "\n")
    f.write("Lesson: " + lesson + "\n")
    f.write("Telephone: " + telephone + "\n")
    f.write("Qualification: " + qualification + "\n")
    f.write("Age: " + age + "\n")
    f.write("Teaching Experiences: " + teachExp + "\n")
    f.write("ID: " + id + "\n")
    f.close()